In [ ]:
!pip install  watson-machine-learning-client

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 538 kB 5.2 MB/s 
     |████████████████████████████████| 132 kB 55.6 MB/s 
     |████████████████████████████████| 55 kB 4.3 MB/s 
     |████████████████████████████████| 9.9 MB 64.4 MB/s 
     |████████████████████████████████| 79 kB 7.2 MB/s 
     |████████████████████████████████| 140 kB 47.9 MB/s 
     |████████████████████████████████| 956 kB 45.8 MB/s 
     |████████████████████████████████| 135 kB 55.2 MB/s 
     |████████████████████████████████| 62 kB 1.7 MB/s 
  Created wheel for ibm-cos-sdk: filename=ibm_cos_sdk-2.12.0-py3-none-any.whl size=73931 sha256=cddb213dd2691ee6d5bbc5b27cdf8c1a0d9bc2134a72f545c35656e55bb74f47
  Stored in directory: /root/.cache/pip/wheels/ec/94/29/2b57327cf00664b6614304f7958abd29d77ea0e5bbece2ea57
  Created wheel for ibm-cos-sdk-core: filename=ibm_cos_sdk_core-2.12.0-py3-none-any.whl size=562962 sha256=1c656239098

In [ ]:
from ibm_watson_machine_learning import APIClient
wml_credentials={
    "url":"https://us-south.ml.cloud.ibm.com",
    "apikey":"BPFGcOrCf3sroRy3uKOPGozsmIL-5oVDv4A_lru2IpMS"
    
}

client=APIClient(wml_credentials)

In [ ]:
client=APIClient(wml_credentials)

In [ ]:

client

In [ ]:
 def guid_from_space_name(client, space_name):
     space=client.spaces.get_details()
     #print(space)
     return(next(item for item in space['resources'] if item['entity']['name']== space_name)['metadata']['id'])

In [ ]:
space_uid=guid_from_space_name(client,'imageclassification') #imageclassification is the deployment space name
print("Space UID ="+space_uid)

Space UID =ba02adea-7e10-4237-81e7-eaf084fe4102

In [ ]:
client.set.default_space(space_uid)

'SUCCESS'

In [ ]:
client.repository.download("f3e12114-24f4-4bae-9d60-2897d27e7ce6", 'nutrition.tar.gz')

Successfully saved model content to file: 'nutrition.tar.gz'
'C:\\Users\\karup\\Downloads/nutrition.tar.gz'

In [ ]:
from keras.models import load_model
from keras.preprocessing import image

In [ ]:
model = load_model("nutrition.h5")

In [ ]:
import numpy as np

In [ ]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("apple.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 1s 696ms/step
array([0], dtype=int64)

In [ ]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result

'APPLES'

In [ ]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("banana.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 0s 40ms/step
array([1], dtype=int64)

In [ ]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result

'BANANA'

In [ ]:
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
#loading of the image
img = load_img("Test_Image5.jpg", grayscale=False,target_size=(64,64))
#image to array 
x = img_to_array(img)
#changing the shape
x= np.expand_dims(x,axis = 0)
predict_x=model.predict(x)
classes_x=np.argmax(predict_x,axis = -1)
classes_x

1/1 [==============================] - 0s 40ms/step
array([3], dtype=int64)

In [ ]:
index=['APPLES', 'BANANA', 'ORANGE', 'PINEAPPLE', 'WATERMELON']
result=str(index[classes_x[0]])
result


'PINEAPPLE'